# Generated by Django 3.2.15 on 2026-07-01 18:18

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Código')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio prevista')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin prevista')),
                ('real_start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio real')),
                ('real_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin real')),
                ('status', models.CharField(choices=[('not_started', 'No iniciado'), ('in_progress', 'En curso'), ('completed', 'Finalizado'), ('delayed', 'Retrasado'), ('cancelled', 'Cancelado')], db_index=True, default='not_started', max_length=32, verbose_name='Estado')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de avance')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='ActivityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Full Name')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Usuario de Actividad',
                'verbose_name_plural': 'Usuarios de Actividad',
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('approved_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Presupuesto aprobado')),
                ('modified_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Presupuesto modificado')),
            ],
            options={
                'verbose_name': 'Partida presupuestaria',
                'verbose_name_plural': 'Partidas presupuestarias',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(default='', verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Importe')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved', models.BooleanField(default=False, verbose_name='Movido')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre')),
                ('proj_file', models.FileField(blank=True, help_text='Select file to upload', upload_to=projects.models.upload_client_file, verbose_name='Fichero')),
            ],
            options={
                'verbose_name': 'Fichero',
                'verbose_name_plural': 'Ficheros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Financier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nombre')),
                ('financier_type', models.CharField(choices=[('public', 'Público'), ('private', 'Privado'), ('foundation', 'Fundación'), ('international', 'Organismo internacional'), ('own_funds', 'Fondos propios'), ('other', 'Otros')], default='other', max_length=32, verbose_name='Tipo')),
                ('tax_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='CIF/NIF')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Persona contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Teléfono')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Financiador',
                'verbose_name_plural': 'Financiadores',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255, verbose_name='Proveedor')),
                ('number', models.CharField(max_length=120, verbose_name='Número')),
                ('issue_date', models.DateField(verbose_name='Fecha emisión')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha pago')),
                ('concept', models.TextField(verbose_name='Concepto')),
                ('taxable_base', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Base imponible')),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Impuestos')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Importe total')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Moneda')),
                ('document_pdf', models.FileField(blank=True, upload_to='projects/invoices/', verbose_name='Documento PDF')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('paid', 'Pagada'), ('justified', 'Justificada'), ('rejected', 'Rechazada')], db_index=True, default='draft', max_length=32, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='projects.activity', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('objective_type', models.CharField(choices=[('general', 'General'), ('specific', 'Específico')], max_length=32, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('not_started', 'No iniciado'), ('in_progress', 'En curso'), ('completed', 'Finalizado'), ('delayed', 'Retrasado'), ('cancelled', 'Cancelado')], db_index=True, default='not_started', max_length=32, verbose_name='Estado')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de avance')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Código')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('completed', 'Finalizado'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=32, verbose_name='Estado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.CharField(blank=True, default='', max_length=255, verbose_name='Fecha de ejecución')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='País')),
                ('region', models.CharField(blank=True, default='', max_length=120, verbose_name='Región')),
                ('locality', models.CharField(blank=True, default='', max_length=120, verbose_name='Localidad')),
                ('approved_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Presupuesto aprobado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('financial_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_projects', to=settings.AUTH_USER_MODEL, verbose_name='Responsable financiero')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('technical_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_projects', to=settings.AUTH_USER_MODEL, verbose_name='Responsable técnico')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('desc', models.TextField(default='', verbose_name='Descripción')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='projects.project')),
            ],
            options={
                'verbose_name': 'Texto alternativo',
                'verbose_name_plural': 'Textos alternativos',
            },
        ),
        migrations.CreateModel(
            name='SubBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('assigned_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Presupuesto asignado')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_lines', to='projects.budgetline', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'Subpartida',
                'verbose_name_plural': 'Subpartidas',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('expected_result', models.TextField(verbose_name='Resultado esperado')),
                ('obtained_result', models.TextField(blank=True, verbose_name='Resultado obtenido')),
                ('evidence', models.TextField(blank=True, verbose_name='Evidencias')),
                ('compliance_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje cumplimiento')),
                ('status', models.CharField(choices=[('not_started', 'No iniciado'), ('in_progress', 'En curso'), ('completed', 'Finalizado'), ('delayed', 'Retrasado'), ('cancelled', 'Cancelado')], db_index=True, default='not_started', max_length=32, verbose_name='Estado')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='projects.objective', verbose_name='Objetivo')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
        migrations.CreateModel(
            name='ProjectFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Importe comprometido')),
                ('granted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Importe concedido')),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Importe desembolsado')),
                ('agreement_date', models.DateField(blank=True, null=True, verbose_name='Fecha convenio')),
                ('agreement_document', models.FileField(blank=True, upload_to='projects/agreements/', verbose_name='Documento convenio')),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_financiers', to='projects.financier', verbose_name='Financiador')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_financiers', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Financiador de proyecto',
                'verbose_name_plural': 'Financiadores de proyecto',
            },
        ),
        migrations.AddField(
            model_name='objective',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('document', models.FileField(upload_to='projects/invoice-documents/', verbose_name='Documento')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Documento anexo de factura',
                'verbose_name_plural': 'Documentos anexos de factura',
            },
        ),
        migrations.CreateModel(
            name='InvoiceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Importe imputado')),
                ('allocated_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje imputado')),
                ('allocation_date', models.DateField(default=datetime.date.today, verbose_name='Fecha imputación')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_allocations', to='projects.activity', verbose_name='Actividad')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_allocations', to='projects.budgetline', verbose_name='Partida')),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_allocations', to='projects.financier', verbose_name='Financiador')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.invoice', verbose_name='Factura')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='projects.project', verbose_name='Proyecto')),
                ('sub_budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_allocations', to='projects.subbudgetline', verbose_name='Subpartida')),
            ],
            options={
                'verbose_name': 'Imputación de factura',
                'verbose_name_plural': 'Imputaciones de facturas',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('baseline', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Línea base')),
                ('target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Meta')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor actual')),
                ('unit', models.CharField(blank=True, max_length=64, verbose_name='Unidad')),
                ('measurement_frequency', models.CharField(blank=True, max_length=120, verbose_name='Frecuencia de medición')),
                ('verification_source', models.TextField(blank=True, verbose_name='Fuente de verificación')),
                ('last_update', models.DateField(blank=True, null=True, verbose_name='Fecha última actualización')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='projects.objective', verbose_name='Objetivo')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_indicators', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(default='', verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Importe')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='projects.project')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField(default=False, verbose_name='Solo lectura')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='projects.folder', verbose_name='Carpeta')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='FinancierContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Importe')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financier_contributions', to='projects.budgetline', verbose_name='Partida')),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_contributions', to='projects.financier', verbose_name='Financiador')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financier_contributions', to='projects.project', verbose_name='Proyecto')),
                ('sub_budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financier_contributions', to='projects.subbudgetline', verbose_name='Subpartida')),
            ],
            options={
                'verbose_name': 'Aportación de financiador',
                'verbose_name_plural': 'Aportaciones de financiadores',
            },
        ),
        migrations.AddIndex(
            model_name='financier',
            index=models.Index(fields=['name'], name='projects_fi_name_e65c13_idx'),
        ),
        migrations.AddIndex(
            model_name='financier',
            index=models.Index(fields=['tax_id'], name='projects_fi_tax_id_2ac8da_idx'),
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.folder', verbose_name='Carpeta'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='activityuser',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='projects.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='projects.objective', verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddIndex(
            model_name='subbudgetline',
            index=models.Index(fields=['budget_line', 'code'], name='projects_su_budget__56c448_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subbudgetline',
            unique_together={('budget_line', 'code')},
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['objective', 'status'], name='projects_re_objecti_7d67b8_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfinancier',
            index=models.Index(fields=['project', 'financier'], name='projects_pr_project_b9248c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectfinancier',
            unique_together={('project', 'financier')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='projects_pr_code_80abae_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['country'], name='projects_pr_country_b1c2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['project', 'objective_type'], name='projects_ob_project_cda2d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='objective',
            unique_together={('project', 'code')},
        ),
        migrations.AddIndex(
            model_name='invoiceallocation',
            index=models.Index(fields=['project', 'activity'], name='projects_in_project_781d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceallocation',
            index=models.Index(fields=['budget_line', 'sub_budget_line'], name='projects_in_budget__fc94f6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceallocation',
            index=models.Index(fields=['financier'], name='projects_in_financi_ebd9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['project', 'status'], name='projects_in_project_7b9f13_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['number'], name='projects_in_number_24d6a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('project', 'provider', 'number')},
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['objective'], name='projects_in_objecti_9a6f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='financiercontribution',
            index=models.Index(fields=['project', 'financier'], name='projects_fi_project_80289c_idx'),
        ),
        migrations.AddIndex(
            model_name='financiercontribution',
            index=models.Index(fields=['budget_line'], name='projects_fi_budget__8abbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='financiercontribution',
            index=models.Index(fields=['sub_budget_line'], name='projects_fi_sub_bud_c248c0_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['project', 'code'], name='projects_bu_project_0547da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('project', 'code')},
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['project', 'status'], name='projects_ac_project_4cf31a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('project', 'code')},
        ),
    ]
