# Generated by Django 3.2.15 on 2026-07-01 18:21

from django.db import migrations, models


def sync_legacy_projects_schema(apps, schema_editor):
    """Bring pre-migration projects tables in line with the generated initial state.

    The project app existed without migrations. Restored databases can therefore
    contain the legacy tables while django_migrations already marks 0001 as
    applied. This data migration creates the missing tables/columns before the
    real 0002 constraints are added.
    """
    existing_tables = set(schema_editor.connection.introspection.table_names())

    def get_model(model_name):
        return apps.get_model("projects", model_name)

    def column_names(table_name):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT * FROM %s LIMIT 0" % schema_editor.quote_name(table_name))
            return {column[0] for column in cursor.description}

    def create_table_if_missing(model_name):
        nonlocal existing_tables
        model = get_model(model_name)
        if model._meta.db_table not in existing_tables:
            schema_editor.create_model(model)
            existing_tables = set(schema_editor.connection.introspection.table_names())

    def add_field_if_missing(model_name, field_name, default=None):
        model = get_model(model_name)
        table_name = model._meta.db_table
        field = model._meta.get_field(field_name)
        if field.column in column_names(table_name):
            return
        field = field.clone()
        field.set_attributes_from_name(field_name)
        field.model = model
        if getattr(field, "remote_field", None) and isinstance(field.remote_field.model, str):
            app_label, model_name = field.remote_field.model.split(".")
            field.remote_field.model = apps.get_model(app_label, model_name)
        if getattr(field, "remote_field", None) and field.remote_field.field_name is None:
            field.remote_field.field_name = field.remote_field.model._meta.pk.name
        if default is not None:
            field.default = default
        schema_editor.add_field(model, field)

    create_table_if_missing("Financier")
    create_table_if_missing("Objective")
    create_table_if_missing("BudgetLine")

    for field_name, default in (
        ("code", ""),
        ("status", None),
        ("start_date", None),
        ("finish_date", None),
        ("country", None),
        ("region", None),
        ("locality", None),
        ("technical_manager", None),
        ("financial_manager", None),
        ("approved_budget", None),
        ("notes", None),
    ):
        add_field_if_missing("Project", field_name, default)

    for field_name, default in (
        ("objective", None),
        ("code", ""),
        ("responsible", None),
        ("location", ""),
        ("planned_start_date", None),
        ("planned_end_date", None),
        ("real_start_date", None),
        ("real_end_date", None),
        ("status", None),
        ("progress_percentage", None),
    ):
        add_field_if_missing("Activity", field_name, default)

    create_table_if_missing("Indicator")
    create_table_if_missing("Result")
    create_table_if_missing("SubBudgetLine")
    create_table_if_missing("ProjectFinancier")
    create_table_if_missing("Invoice")
    create_table_if_missing("InvoiceDocument")
    create_table_if_missing("FinancierContribution")
    create_table_if_missing("InvoiceAllocation")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(sync_legacy_projects_schema, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(check=models.Q(('progress_percentage__gte', 0), ('progress_percentage__lte', 100)), name='activity_progress_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(check=models.Q(('approved_budget__gte', 0)), name='budget_line_approved_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(check=models.Q(('modified_budget__gte', 0)), name='budget_line_modified_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='expense_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='financiercontribution',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='financier_contribution_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='financiercontribution',
            constraint=models.CheckConstraint(check=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='financier_contribution_pct_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='financiercontribution',
            constraint=models.CheckConstraint(check=models.Q(('budget_line__isnull', False), ('sub_budget_line__isnull', False), _connector='OR'), name='financier_contribution_has_budget_target'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='income_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('taxable_base__gte', 0)), name='invoice_taxable_base_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('taxes__gte', 0)), name='invoice_taxes_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='invoice_total_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='invoiceallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocated_amount__gte', 0)), name='invoice_allocation_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='invoiceallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocated_percentage__gte', 0), ('allocated_percentage__lte', 100)), name='invoice_allocation_pct_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='objective',
            constraint=models.CheckConstraint(check=models.Q(('progress_percentage__gte', 0), ('progress_percentage__lte', 100)), name='objective_progress_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('approved_budget__gte', 0)), name='project_approved_budget_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='projectfinancier',
            constraint=models.CheckConstraint(check=models.Q(('committed_amount__gte', 0)), name='project_financier_committed_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='projectfinancier',
            constraint=models.CheckConstraint(check=models.Q(('granted_amount__gte', 0)), name='project_financier_granted_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='projectfinancier',
            constraint=models.CheckConstraint(check=models.Q(('disbursed_amount__gte', 0)), name='project_financier_disbursed_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(check=models.Q(('compliance_percentage__gte', 0), ('compliance_percentage__lte', 100)), name='result_compliance_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='subbudgetline',
            constraint=models.CheckConstraint(check=models.Q(('assigned_budget__gte', 0)), name='sub_budget_line_assigned_gte_0'),
        ),
    ]
