# Generated by Django 3.2.15 on 2026-07-01 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20260701_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbudgetline',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_lines', to='projects.subbudgetline', verbose_name='Subpartida padre'),
        ),
        migrations.AddIndex(
            model_name='subbudgetline',
            index=models.Index(fields=['parent', 'code'], name='projects_su_parent__cd6360_idx'),
        ),
    ]
