# Generated by Django 3.2.15 on 2026-07-01 23:40

from django.db import migrations, models
import django.db.models.deletion


def migrate_subbudgetlines_to_budgetlines(apps, schema_editor):
    BudgetLine = apps.get_model("projects", "BudgetLine")
    SubBudgetLine = apps.get_model("projects", "SubBudgetLine")
    FinancierContribution = apps.get_model("projects", "FinancierContribution")
    InvoiceAllocation = apps.get_model("projects", "InvoiceAllocation")

    id_map = {}
    pending = list(SubBudgetLine.objects.select_related("budget_line", "parent").order_by("id"))
    while pending:
        next_pending = []
        changed = False
        for sub_line in pending:
            if sub_line.parent_id and sub_line.parent_id not in id_map:
                next_pending.append(sub_line)
                continue
            parent_id = id_map[sub_line.parent_id] if sub_line.parent_id else sub_line.budget_line_id
            new_line = BudgetLine.objects.create(
                project_id=sub_line.budget_line.project_id,
                parent_id=parent_id,
                code=sub_line.code,
                name=sub_line.name,
                description=sub_line.description,
                approved_budget=sub_line.assigned_budget,
                modified_budget=0,
            )
            id_map[sub_line.id] = new_line.id
            changed = True
        if not changed:
            raise RuntimeError("No se pudo migrar la jerarquía de subpartidas presupuestarias.")
        pending = next_pending

    if not id_map:
        return

    with schema_editor.connection.constraint_checks_disabled():
        for old_id, new_id in id_map.items():
            FinancierContribution.objects.filter(sub_budget_line_id=old_id).update(sub_budget_line_id=new_id)
            InvoiceAllocation.objects.filter(sub_budget_line_id=old_id).update(sub_budget_line_id=new_id)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20260701_2320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subbudgetline',
            unique_together=None,
        ),
        migrations.AddField(
            model_name='budgetline',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_lines', to='projects.budgetline', verbose_name='Partida padre'),
        ),
        migrations.RunPython(migrate_subbudgetlines_to_budgetlines, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subbudgetline',
            name='budget_line',
        ),
        migrations.RemoveField(
            model_name='subbudgetline',
            name='parent',
        ),
        migrations.AlterField(
            model_name='financiercontribution',
            name='sub_budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_financier_contributions', to='projects.budgetline', verbose_name='Subpartida'),
        ),
        migrations.AlterField(
            model_name='invoiceallocation',
            name='sub_budget_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_invoice_allocations', to='projects.budgetline', verbose_name='Subpartida'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['parent', 'code'], name='projects_bu_parent__b95018_idx'),
        ),
        migrations.DeleteModel(
            name='SubBudgetLine',
        ),
    ]
