# Generated by Codex on 2026-07-06

from django.core.validators import RegexValidator
from django.db import migrations, models


def to_base36(value):
    alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    value = int(value or 0)
    if value == 0:
        return "0"
    chars = []
    while value:
        value, remainder = divmod(value, 36)
        chars.append(alphabet[remainder])
    return "".join(reversed(chars))


def populate_invoice_identifiers(apps, schema_editor):
    Invoice = apps.get_model("projects", "Invoice")
    for invoice in Invoice.objects.all().order_by("id"):
        changed = False
        if not invoice.locator:
            invoice.locator = to_base36(invoice.pk).zfill(5)[-5:]
            changed = True
        if not invoice.invoice_code and invoice.issue_date:
            invoice.invoice_code = "{}-{}".format(invoice.issue_date.year, invoice.pk)
            changed = True
        if changed:
            invoice.save(update_fields=["locator", "invoice_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_auto_20260701_2340"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="locator",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=5,
                null=True,
                unique=True,
                validators=[
                    RegexValidator(
                        "^[A-Z0-9]{5}$",
                        "El localizador debe tener 5 caracteres alfanuméricos en mayúsculas.",
                    )
                ],
                verbose_name="Localizador",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_code",
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name="Código de factura"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="provider_tax_id",
            field=models.CharField(blank=True, max_length=32, verbose_name="NIF del proveedor"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["issue_date"], name="projects_in_issue_d_6c140d_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["locator"], name="projects_in_locator_6109e5_idx"),
        ),
        migrations.RunPython(populate_invoice_identifiers, migrations.RunPython.noop),
    ]
