# Generated by Codex on 2026-07-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_remove_invoice_project_activity_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceallocation",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_allocations",
                to="projects.activity",
                verbose_name="Actividad",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceallocation",
            name="sub_budget_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_invoice_allocations",
                to="projects.budgetline",
                verbose_name="Subpartida",
            ),
        ),
        migrations.AddField(
            model_name="invoiceallocation",
            name="financier_contribution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_allocations",
                to="projects.financiercontribution",
                verbose_name="Aportación de financiador",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceallocation",
            index=models.Index(fields=["financier_contribution"], name="projects_in_financi_f3192c_idx"),
        ),
    ]
