# Generated by Django 3.2.15 on 2022-12-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharma', '0003_auto_20221214_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOPDConsents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('document', models.FileField(upload_to='media/lopd_files', verbose_name='Documento firmado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lopd', to='pharma.pacientes', verbose_name='pacientes')),
            ],
        ),
    ]
